### ISSUE TITLE
download data issue

### ISSUE THREAD

**Issue by redna11** [google-research/long-range-arena#1]
Hello,

Trying to get the listops data from gc.

https://console.cloud.google.com/storage/browser/long-range-arena
https://storage.googleapis.com/long-range-arena/lra_release

doesn't work.

gsutil -m cp -R gs://long-range-arena ./lra_release 

gives: "ServiceException: 401 Anonymous caller does not have storage.objects.list access to the Google Cloud Storage bucket."

Any suggestions to improve data accessibility?

thanks

**Comment by vanzytay** [comment]
Hi, 

Thanks for reporting this issue. You can obtain the listops data using

https://storage.cloud.google.com/long-range-arena/lra_release/listops-1000/basic_train.tsv
https://storage.cloud.google.com/long-range-arena/lra_release/listops-1000/basic_val.tsv
https://storage.cloud.google.com/long-range-arena/lra_release/listops-1000/basic_test.tsv

For now, only the files have been set to public but not the entire folder. Do let us know if you're not able to still access the files. 

Thanks!

**Comment by da03** [comment]
@vanzytay I can download listops dataset, but what about other datasets? Can you post filenames of other datasets as well?

**Comment by vanzytay** [comment]
Hi @da03,

You can find the AAN splits here

https://storage.googleapis.com/long-range-arena/lra_release/aan/new_aan_pairs.eval.only_ids.tsv
https://storage.googleapis.com/long-range-arena/lra_release/aan/new_aan_pairs.test.only_ids.tsv
https://storage.googleapis.com/long-range-arena/lra_release/aan/new_aan_pairs.train.only_ids.tsv

The IMDB and Cifar datasets already come with TFDS so you should be able to use them without any issues.

We'll finding a better way to release the Pathfinder and will reply to this thread ASAP when we have a friendlier format to release the folder.

**Comment by vanzytay** [comment]
Hey! 

You can now download the entire data at https://storage.googleapis.com/long-range-arena/lra_release.gz! 

Thanks!

**Comment by mtreviso** [comment]
Hi!

I've just downloaded `lra_release.gz` (which should be properly renamed to `.tar.gz`) and here is the output:
```
lra_release/
├── listops-1000
│   ├── basic_test.tsv
│   ├── basic_train.tsv
│   └── basic_val.tsv
├── lra_release
│   ├── listops-1000
│   ├── pathfinder128
│   ├── pathfinder256
│   ├── pathfinder32
│   ├── pathfinder64
│   └── tsv_data
└── pathfinder128
    └── curv_baseline
```

So, it is missing the text classification data. Can I just use the dataset provided [in here](https://ai.stanford.edu/~amaas/data/sentiment/) and the `lra` code will take care of the rest? 

Best,
