### ISSUE TITLE
Tied weights for ListOps Transformer

### ISSUE THREAD

**Issue by adamsolomou** [google-research/long-range-arena#10]
Hi, 

According to the [configuration file](https://github.com/google-research/long-range-arena/blob/main/lra_benchmarks/listops/configs/base_listops_config.py) the transformer model (with vanilla softmax attention) used in the ListOps task is weight tied (for both self-attention module and the feedforward network). Does that also apply to the other transformer variants listed in the comparison? For example, is Linear Transformer also weight-tied? I couldn't find anything relevant in the paper. 

Many thanks in advance!

**Comment by vanzytay** [comment]
Hi @adamsolomou. Yes, if the base transformer config is tied, then all other transformers have tied weights as well. We use pretty much the same base config script for all models. 

We're working on a 2nd release with (hopefully) more details of the other models and implementation.
