### ISSUE TITLE
Why a Custom Embed Class ?

### ISSUE THREAD

**Issue by SauravMaheshkar** [google-research/long-range-arena#5]
In the [models/layers/common_layers.py](https://github.com/google-research/long-range-arena/blob/main/lra_benchmarks/models/layers/common_layers.py) file a custom layer was created at line [25](https://github.com/google-research/long-range-arena/blob/211e07deebf7941e203e759585da0091137c0d25/lra_benchmarks/models/layers/common_layers.py#L23) which was not used. 

Even in the [models/transformer/transformer.py](https://github.com/google-research/long-range-arena/blob/main/lra_benchmarks/models/transformer/transformer.py) the core nn.Embed layer was used. 

Are both the modules same? If not, is the defined Embed class redundant?

**Comment by vanzytay** [comment]
Hey there,

This code is an excerpt from the fully planned release (with other Jax/Flax models and all). We plan to update it in the coming weeks. Thats why you might observe some artifacts of this around the codebase.

**Comment by SauravMaheshkar** [comment]
Thanks a lot for the quick response. 😄
